# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: scimad | blog
email: scimad2.71@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, this is my personal blog. I plan to write the stories of my life here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scimad.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
twitter_username: scimad
github_username:  scimad

# Build settings
markdown: kramdown


plugins_dir:
  - jekyll-seo-tag
